apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mocops
spec:
  destinations:
  - namespace: '*'
    server: 'https://api.ocp-prod.massopen.cloud:6443'
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
