apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-resources
spec:
  destination:
    name: curator
    namespace: argocd
  ignoreDifferences:
    - group: imageregistry.operator.openshift.io
      jsonPointers:
        - /spec/defaultRoute
        - /spec/httpSecret
        - /spec/proxy
        - /spec/requests
        - /spec/rolloutStrategy
      kind: Config
      name: cluster
  project: cluster-management
  source:
    path: cluster-scope/overlays/moc/curator
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
