---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: installplan-operator
spec:
  destination:
    name: zero
    namespace: installplan-operator
  project: installplan-operator
  source:
    path: installplan-operator/overlays/moc/zero
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
